DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    phonenumber CHAR(10) UNIQUE NOT NULL,
    firstname TEXT NOT NULL,
    lastname TEXT NOT NULL,
    email TEXT,
    check_in_state BINARY,
    account_activated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_check_in TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_check_out TIMESTAMP
);

CREATE TABLE time_sheet (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    check_in_state BINARY NOT NULL,
    time_in TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    time_out TIMESTAMP,
    time_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    time_stamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    foreign key (user_id) REFERENCES user (id)
);